version: '3.7'

services:
  webserver:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${http_proxy}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${https_proxy}
        - FTP_PROXY=${FTP_PROXY}
        - ftp_proxy=${ftp_proxy}

    environment: 
      app_server : ${app_server}

    volumes:
      - ./webserver:/src
      - node_modules:/src/node_modules
    container_name: webserver
    ports:
      - "8080:80"

volumes:
  node_modules: