version: '3'
services: 
  appserver:
    container_name: appserver
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${http_proxy}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${https_proxy}
        - FTP_PROXY=${FTP_PROXY}
        - ftp_proxy=${ftp_proxy}

    ipc: host
    volumes: 
      - ./:/workspace
    
    ports:
      - "80:8000"
    tty: true
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu, utility, compute]